# Generated by Django 6.0.5 on 2026-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social (para RUC)', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción opcional (sobre escribe product.name)', max_length=200),
        ),
    ]
