# Generated by Django 5.0.14 on 2026-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_groups', '0001_initial'),
        ('core_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core_permissions.permission'),
        ),
    ]
