# Generated by Django 5.0.14 on 2026-05-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps.facturacion", "0001_initial"),
        ("apps.inventory", "0001_initial"),
        ("django.db.backends.base.operations",),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("draft", "Borrador"),
                            ("sent", "Enviada"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                            ("expired", "Expirada"),
                        ],
                        default="draft",
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="facturacion.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_lines",
                        to="inventory.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Cotización",
                "verbose_name_plural": "Líneas de Cotización",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("delivery_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("partial", "Parcial"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="facturacion.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Venta",
                "verbose_name_plural": "Órdenes de Venta",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Orden",
                "verbose_name_plural": "Líneas de Orden",
            },
        ),
    ]
