# Generated by Django 5.0.14 on 2026-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_users", "0002_remove_userprofile_user_id_userprofile_groups_and_more"),
        ("core_companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="active_users",
                to="core_companies.company",
            ),
        ),
    ]
