from pathlib import Path

from django.conf import settings

from .models import EnabledModule


def write_modules_enabled() -> Path:
    target = Path(settings.BASE_DIR) / "erp_nexus" / "modules_enabled.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    apps = list(EnabledModule.objects.filter(status="active").values_list("django_app", flat=True))

    content_lines = [
        "# Auto-generated by apply_modules. Do not edit manually.",
        "MODULE_APPS = [",
    ]
    for app in apps:
        content_lines.append(f'    "{app}",')
    content_lines.append("]")
    content = "\n".join(content_lines) + "\n"

    target.write_text(content, encoding="utf-8")
    return target
