# Generated by Django 5.0.14 on 2026-04-01 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(help_text='ID único de la instancia', max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('environment', models.CharField(default='production', max_length=20)),
                ('domain', models.CharField(blank=True, default='', max_length=200)),
                ('total_users', models.IntegerField(default=0)),
                ('total_companies', models.IntegerField(default=0)),
                ('total_modules_installed', models.IntegerField(default=0)),
                ('total_modules_active', models.IntegerField(default=0)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('db_status', models.CharField(default='ok', max_length=20)),
                ('cache_status', models.CharField(default='ok', max_length=20)),
                ('disk_usage_percent', models.FloatField(default=0)),
                ('memory_usage_percent', models.FloatField(default=0)),
                ('active_users_count', models.IntegerField(default=0)),
                ('pending_events', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric_type', models.CharField(choices=[('api_requests', 'API Requests'), ('logins', 'Logins'), ('module_installs', 'Module Installs'), ('module_activations', 'Module Activations'), ('errors', 'Errors')], db_index=True, max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Usage Metric',
                'verbose_name_plural': 'Usage Metrics',
                'ordering': ['-date'],
                'unique_together': {('date', 'metric_type')},
            },
        ),
    ]
