# Generated by Django 6.0.5 on 2026-05-13 22:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_companies', '0002_company_address_company_email_and_more'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'Ventas'), ('purchases', 'Compras'), ('marketplace', 'Marketplace')], help_text='Módulo al que aplica la regla', max_length=20)),
                ('commission_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Fijo')], default='percentage', help_text='Tipo de comisión: porcentaje o monto fijo', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión (5.5 = 5.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para aplicar la regla', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo para aplicar la regla (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la regla está activa')),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='IDs de categorías, proveedores, etc. a los que aplica')),
                ('created_by', models.CharField(blank=True, help_text='Usuario que creó la regla', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Comisión',
                'verbose_name_plural': 'Reglas de Comisión',
                'ordering': ['module', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutConfig',
            fields=[
                ('company', models.OneToOneField(help_text='Empresa (relación uno a uno)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payout_config', serialize=False, to='core_companies.company')),
                ('auto_approve', models.BooleanField(default=False, help_text='Aprobar pagos automáticamente')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de retención (ej: 10.0 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('retain_until_threshold', models.DecimalField(decimal_places=2, default=100.0, help_text='Monto mínimo acumulado para generar pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_schedule', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', help_text='Frecuencia de generación de pagos', max_length=20)),
                ('notify_emails', models.JSONField(blank=True, default=list, help_text='Lista de correos para notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuraciones de Pagos',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(choices=[('produbanco', 'Produbanco'), ('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('pacifico', 'Banco del Pacífico'), ('solidario', 'Banco Solidario'), ('internacional', 'Banco Internacional'), ('loja', 'Banco de Loja'), ('coops', 'Coops')], help_text='Banco emisor de la cuenta', max_length=20)),
                ('account_number', models.CharField(help_text='Número de cuenta bancaria', max_length=50)),
                ('account_type', models.CharField(choices=[('checking', 'Corriente'), ('savings', 'Ahorros')], default='checking', help_text='Tipo de cuenta (Corriente/Ahorros)', max_length=20)),
                ('rut', models.CharField(blank=True, help_text='RUC o cédula del titular (opcional)', max_length=20)),
                ('account_holder_name', models.CharField(help_text='Nombre del titular de la cuenta', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la cuenta está activa')),
                ('is_default', models.BooleanField(default=False, help_text='Cuenta predeterminada para pagos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa propietaria de la cuenta', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core_companies.company')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Referencia única del pago (ej: PAY-20260513-0001)', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Moneda del pago (USD, EUR, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='draft', help_text='Estado actual del pago', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción o notas adicionales')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha y hora de pago efectivo', null=True)),
                ('bank_reference', models.CharField(blank=True, help_text='Referencia bancaria del pago', max_length=200)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el pago falla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Usuario que aprobó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(help_text='Cuenta bancaria destino', on_delete=django.db.models.deletion.PROTECT, to='payouts.bankaccount')),
                ('company', models.ForeignKey(help_text='Empresa beneficiaria', on_delete=django.db.models.deletion.CASCADE, to='core_companies.company')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto bruto antes de retenciones', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto retenido', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto neto a pagar (bruto - retenciones)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_type', models.CharField(help_text='Tipo de comisión aplicada', max_length=50)),
                ('description', models.CharField(help_text='Descripción breve del concepto', max_length=200)),
                ('order', models.ForeignKey(blank=True, help_text='Orden de venta asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order')),
                ('payout', models.ForeignKey(help_text='Pago al que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payouts.payout')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Orden de compra asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Línea de Pago',
                'verbose_name_plural': 'Líneas de Pago',
                'ordering': ['id'],
            },
        ),
    ]
