# Generated by Django 6.0.5 on 2026-05-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_companies', '0002_company_address_company_email_and_more'),
        ('payouts', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Comisión antes de retención', max_digits=12)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, help_text='Retención SRI aplicada', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Neto a pagar', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payouts.commissionrule')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_companies.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_records', to='sales.order')),
                ('payout_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_records', to='payouts.payoutitem')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_records', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Registro de Comisión',
                'verbose_name_plural': 'Registros de Comisión',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='payouts_com_company_3d2353_idx')],
            },
        ),
    ]
