# Generated by Django 6.0.5 on 2026-05-13 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_commissionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrecord',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de creación del registro'),
        ),
    ]
