# Generated by Django 5.0.14 on 2026-05-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_companies', '0002_company_address_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnabledModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_name', models.CharField(max_length=100, unique=True)),
                ('django_app', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('module_type', models.CharField(choices=[('essential', 'Essential (core)'), ('optional', 'Optional Plugin'), ('plugin', 'Third-party Plugin')], default='optional', max_length=20)),
                ('repo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('min_erp_version', models.CharField(blank=True, help_text='Minimum ERP version required', max_length=50)),
                ('max_erp_version', models.CharField(blank=True, help_text='Maximum ERP version compatible', max_length=50, null=True)),
                ('python_dependencies', models.JSONField(blank=True, default=dict, help_text='Python package dependencies')),
                ('system_dependencies', models.JSONField(blank=True, default=dict, help_text='System binary dependencies')),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('is_licensed', models.BooleanField(default=False, help_text='If True, module requires a valid license to install')),
                ('license_required', models.BooleanField(default=False, help_text='If True, a license key is mandatory')),
                ('trial_days', models.IntegerField(default=0, help_text='Number of trial days (0 = no trial)')),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price', max_digits=10, null=True)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly subscription price', max_digits=10, null=True)),
                ('installed_path', models.CharField(blank=True, max_length=500, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('django_app', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_menu', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('downloaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Module Download',
                'verbose_name_plural': 'Module Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('github', 'GitHub Repository'), ('git', 'Git Repository'), ('url', 'URL (JSON catalog)'), ('local', 'Local Path')], default='github', max_length=20)),
                ('url', models.URLField(help_text='URL del repositorio o catálogo', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=50, help_text='Prioridad de búsqueda (mayor = primero)')),
                ('cached_modules', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module Registry',
                'verbose_name_plural': 'Module Registries',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Unique license key (auto-generated)', max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('free', 'Free / Open Source'), ('trial', 'Trial (30 days)'), ('paid', 'Paid Subscription'), ('perpetual', 'Perpetual License')], default='free', max_length=20)),
                ('valid_from', models.DateTimeField(auto_now_add=True, help_text='License activation date')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Expiry date (null = perpetual)', null=True)),
                ('max_seats', models.IntegerField(default=1, help_text='Maximum number of installations/seats allowed')),
                ('used_seats', models.IntegerField(default=0, help_text='Current number of active installations')),
                ('is_active', models.BooleanField(default=True, help_text='Whether license can be used for new installs')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Extra features {"support": "premium", "updates": true}')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this license')),
                ('company', models.ForeignKey(blank=True, help_text='Company this license is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_companies.company')),
                ('module', models.ForeignKey(help_text='Module this license applies to', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core_marketplace.modulecatalogitem')),
            ],
            options={
                'verbose_name': 'Module License',
                'verbose_name_plural': 'Module Licenses',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['license_key'], name='core_market_license_b97091_idx'), models.Index(fields=['module', 'is_active'], name='core_market_module__368226_idx')],
            },
        ),
    ]
