# Generated by Django 5.0.14 on 2026-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecatalogitem',
            name='admin_menu',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='django_app',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='installed_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='max_erp_version',
            field=models.CharField(blank=True, help_text='Maximum ERP version compatible', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='min_erp_version',
            field=models.CharField(blank=True, help_text='Minimum ERP version required', max_length=50),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='module_type',
            field=models.CharField(choices=[('essential', 'Essential (core)'), ('optional', 'Optional Plugin'), ('plugin', 'Third-party Plugin')], default='optional', max_length=20),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='python_dependencies',
            field=models.JSONField(blank=True, default=dict, help_text='{"packages": ["celery", "redis"]}'),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='system_dependencies',
            field=models.JSONField(blank=True, default=dict, help_text='{"bin": ["wkhtmltopdf"], "apt": []}'),
        ),
    ]
