# Generated by Django 5.0.14 on 2026-05-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecatalogitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción del módulo para marketplace y catálogo'),
        ),
    ]
