# Generated by Django 5.0.14 on 2026-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecatalogitem',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='installed_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulecatalogitem',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
