# Generated by Django 5.0.14 on 2026-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_marketplace", "0002_modulecatalogitem_installed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulecatalogitem",
            name="admin_menu",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modulecatalogitem",
            name="django_app",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="EnabledModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("technical_name", models.CharField(max_length=100, unique=True)),
                ("django_app", models.CharField(max_length=200)),
                ("status", models.CharField(default="active", max_length=20)),
                ("enabled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
