# Generated by Django 5.0.14 on 2026-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0002_add_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecatalogitem',
            name='admin_menu_category',
            field=models.CharField(blank=True, default='Aplicaciones', help_text='Categoria en el menu lateral (ej: Ventas, Inventario, Contabilidad)', max_length=100),
        ),
    ]
