# Generated by Django 5.0.14 on 2026-05-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0003_add_admin_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleVersionConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('equal', '='), ('approx_equal', '~'), ('caret', '^'), ('greater', '>'), ('greater_equal', '>='), ('less', '<'), ('less_equal', '<=')], default='equal', help_text='Type of version constraint', max_length=20)),
                ('version', models.CharField(help_text='Version string (e.g. "1.2.3", ">=1.0.0", "^2.0.0")', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of this constraint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module that declares this constraint', on_delete=django.db.models.deletion.CASCADE, related_name='version_constraints', to='core_marketplace.modulecatalogitem')),
            ],
            options={
                'verbose_name': 'Module Version Constraint',
                'verbose_name_plural': 'Module Version Constraints',
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, help_text='If True, this dependency is mandatory (hard requirement)')),
                ('conflict', models.BooleanField(default=False, help_text='If True, this module cannot coexist with depends_on')),
                ('description', models.TextField(blank=True, default='', help_text='Why this dependency exists or conflict reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(help_text='Module that is required/optional/conflicted', on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core_marketplace.modulecatalogitem')),
                ('module', models.ForeignKey(help_text='Module that declares the dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core_marketplace.modulecatalogitem')),
                ('version_constraint', models.ForeignKey(blank=True, help_text='Optional version constraint for this dependency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_marketplace.moduleversionconstraint')),
            ],
            options={
                'verbose_name': 'Module Dependency',
                'verbose_name_plural': 'Module Dependencies',
            },
        ),
        migrations.AddIndex(
            model_name='moduleversionconstraint',
            index=models.Index(fields=['module', 'constraint_type'], name='core_market_module__00cc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='moduledependency',
            index=models.Index(fields=['module', 'required'], name='core_market_module__260daf_idx'),
        ),
        migrations.AddIndex(
            model_name='moduledependency',
            index=models.Index(fields=['depends_on'], name='core_market_depends_4bf0c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduledependency',
            unique_together={('module', 'depends_on')},
        ),
    ]
