# Generated by Django 5.0.14 on 2026-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0003_modulecatalogitem_django_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('downloaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Module Download',
                'verbose_name_plural': 'Module Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('github', 'GitHub Repository'), ('git', 'Git Repository'), ('url', 'URL (JSON catalog)'), ('local', 'Local Path')], default='github', max_length=20)),
                ('url', models.URLField(help_text='URL del repositorio o catálogo', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=50, help_text='Prioridad de búsqueda (mayor = primero)')),
                ('cached_modules', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module Registry',
                'verbose_name_plural': 'Module Registries',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
