# Generated by Django 5.0.14 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0004_add_version_constraints_and_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='enabledmodule',
            name='installed_version',
            field=models.CharField(default='0.0.0', help_text='Version installed from catalog', max_length=50),
        ),
    ]
