# Generated by Django 5.0.14 on 2026-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_marketplace', '0005_add_installed_version_to_enabledmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecatalogitem',
            name='installed_version',
            field=models.CharField(blank=True, help_text='Version last installed from catalog', max_length=50, null=True),
        ),
    ]
