"""
Utilities for dynamic module loading via modules_enabled.py.

This module provides functions to read/write the modules_enabled.py file
which controls which optional plugins are loaded at Django startup.
"""
from pathlib import Path
from typing import List, Optional

from django.conf import settings


def get_modules_enabled_path() -> Path:
    """Return the path to modules_enabled.py."""
    return Path(settings.BASE_DIR) / "erp_nexus" / "modules_enabled.py"


def read_modules_enabled() -> List[str]:
    """
    Read modules_enabled.py and return list of Django app labels.
    Returns empty list if file doesn't exist or is malformed.
    """
    path = get_modules_enabled_path()
    if not path.exists():
        return []

    try:
        # Execute the file in a restricted namespace
        namespace = {}
        with open(path, "r") as f:
            code = f.read()
        exec(code, namespace)
        modules = namespace.get("MODULE_APPS", [])
        if isinstance(modules, list):
            return modules
        return []
    except Exception:
        # File malformed — return empty to avoid crash
        return []


def write_modules_enabled(technical_names: List[str]) -> None:
    """
    Atomically write MODULE_APPS list to modules_enabled.py.

    Args:
        technical_names: List of module technical names (Django app labels)
    """
    path = get_modules_enabled_path()
    path.parent.mkdir(parents=True, exist_ok=True)

    # Build file content
    lines = [
        "# Auto-generated by ERP Nexus Marketplace. Do NOT edit manually.",
        "# Use `python manage.py module_install/uninstall` to manage plugins.",
        "# Essential modules are defined in INSTALLED_APPS (apps/).",
        "",
        "MODULE_APPS = [",
    ]

    for name in technical_names:
        lines.append(f"    '{name}',")

    lines.append("]")
    content = "\n".join(lines) + "\n"

    # Atomic write — write to temp then rename
    temp_path = path.with_suffix(".py.tmp")
    with open(temp_path, "w") as f:
        f.write(content)

    temp_path.replace(path)


def get_enabled_apps() -> List[str]:
    """
    Get all enabled Django apps including essential + optional.

    Returns:
        List of fully-qualified Django app labels (e.g., ['apps.facturacion', 'hr'])
    """
    # Essential apps from INSTALLED_APPS (filter out plugin-only prefixes)
    from django.conf import settings

    essential_apps = [
        app for app in settings.INSTALLED_APPS
        if not app.startswith("plugins.")  # future plugin namespace
    ]

    # Optional apps from modules_enabled.py
    optional_apps = read_modules_enabled()

    return essential_apps + optional_apps


def is_module_enabled(technical_name: str) -> bool:
    """Check if a module is currently enabled (installed via marketplace)."""
    enabled = read_modules_enabled()
    return technical_name in enabled


def add_to_modules_enabled(technical_name: str) -> None:
    """Add a module to modules_enabled.py (idempotent)."""
    current = read_modules_enabled()
    if technical_name not in current:
        current.append(technical_name)
        write_modules_enabled(current)


def remove_from_modules_enabled(technical_name: str) -> None:
    """Remove a module from modules_enabled.py."""
    current = read_modules_enabled()
    if technical_name in current:
        current = [m for m in current if m != technical_name]
        write_modules_enabled(current)
