# Auto-generated by ERP Nexus Marketplace. Do NOT edit manually.
# Use `python manage.py module_install/uninstall` to manage plugins.
# Essential modules are defined in INSTALLED_APPS (apps/).

MODULE_APPS: list[str] = []
