# Auto-generated by apply_modules. Do not edit manually.
# Plugins instalables van aquí (essential modules van en INSTALLED_APPS directamente)
MODULE_APPS = [
    # Plugins opcionales se agregan aquí cuando se instalan via Marketplace
]
