# Generated by Django 5.0.14 on 2026-04-01 14:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, help_text='ID del usuario', null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(choices=[('auth.login', 'Login'), ('auth.logout', 'Logout'), ('auth.register', 'Registro'), ('auth.password_change', 'Cambio de contraseña'), ('auth.password_reset', 'Reset de contraseña'), ('module.install', 'Instalar módulo'), ('module.uninstall', 'Desinstalar módulo'), ('module.activate', 'Activar módulo'), ('module.deactivate', 'Desactivar módulo'), ('data.create', 'Crear registro'), ('data.update', 'Actualizar registro'), ('data.delete', 'Eliminar registro'), ('api.access', 'Acceso API'), ('system.error', 'Error del sistema')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, default='', help_text='Tipo de recurso (User, Module, Product, etc.)', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict, help_text='Datos adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_audit__action_1d0bd4_idx'), models.Index(fields=['user_id', 'created_at'], name='core_audit__user_id_c40a94_idx'), models.Index(fields=['company_id', 'created_at'], name='core_audit__company_625971_idx')],
            },
        ),
    ]
