# Generated by Django 5.0.14 on 2026-05-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='establishment_code',
            field=models.CharField(default='001', help_text='Código establecimiento (3 dígitos)', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='point_emission_code',
            field=models.CharField(default='001', help_text='Código punto emisión (3 dígitos)', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='ruc',
            field=models.CharField(blank=True, help_text='RUC - 13 dígitos', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Identificación fiscal (cédula/RUC)', max_length=20, null=True),
        ),
    ]
