# Generated by Django 5.0.14 on 2026-05-05 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(choices=[('free', 'Free (10 facturas/mes)'), ('monthly_10', 'Mensual $10/mes'), ('yearly_100', 'Anual $100/año'), ('lifetime_3500', 'Lifetime $3,500 (actualizaciones incluidas)'), ('lifetime_750', 'Lifetime $750 (sin actualizaciones)')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_monthly_equivalent', models.DecimalField(decimal_places=2, help_text='Precio equivalente mensual (para comparación)', max_digits=10)),
                ('max_invoices_per_month', models.IntegerField(default=10, help_text='Límite de facturas por mes (0=ilimitado)')),
                ('allows_updates', models.BooleanField(default=False, help_text='Incluye actualizaciones de nuevas versiones')),
                ('priority_support', models.BooleanField(default=False, help_text='Soporte prioritario (email/chat directo)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Licencia',
                'verbose_name_plural': 'Tipos de Licencia',
            },
        ),
        migrations.CreateModel(
            name='SriAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ambiente SRI',
                'verbose_name_plural': 'Ambientes SRI',
            },
        ),
        migrations.CreateModel(
            name='SriImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto SRI',
                'verbose_name_plural': 'Impuestos SRI',
            },
        ),
        migrations.CreateModel(
            name='SriTipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo Comprobante SRI',
                'verbose_name_plural': 'Tipos Comprobante SRI',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor final')], max_length=5)),
                ('identification_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core_companies.company')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('company', 'identification_type', 'identification_number')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='001-001-0000000001', max_length=30)),
                ('date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ambiente', models.IntegerField(choices=[(1, 'Pruebas'), (2, 'Producción')], default=1)),
                ('sri_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente envío'), ('sent', 'Enviada a SRI'), ('accepted', 'Aceptada SRI'), ('rejected', 'Rechazada SRI'), ('cancelled', 'Anulada')], default='pending', max_length=20)),
                ('sri_authorization_date', models.DateTimeField(blank=True, null=True)),
                ('sri_message', models.TextField(blank=True, help_text='Mensaje respuesta SRI')),
                ('sri_xml_autorizado', models.TextField(blank=True, help_text='XML autorizado por SRI')),
                ('access_key', models.CharField(help_text='Clave acceso SRI (49 dígitos)', max_length=50, unique=True)),
                ('xml_content', models.TextField(blank=True, help_text='XML firmado (enviado)')),
                ('xml_original_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core_companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facturacion_ec.customer')),
                ('tipo_comprobante', models.ForeignKey(default='01', on_delete=django.db.models.deletion.PROTECT, to='facturacion_ec.sritipocomprobante')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('01', 'Factura'), ('04', 'Nota de Crédito'), ('05', 'Nota de Débito'), ('06', 'Guía de Remisión'), ('07', 'Comprobante de Retención')], max_length=2)),
                ('access_key', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('xml_original', models.TextField(help_text='XML original generado')),
                ('xml_signed', models.TextField(help_text='XML firmado digitalmente')),
                ('xml_autorizado', models.TextField(blank=True, help_text='XML devuelto por SRI')),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_companies.company')),
                ('created_from_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_documents', to='facturacion_ec.invoice')),
            ],
            options={
                'verbose_name': 'Documento Electrónico',
                'verbose_name_plural': 'Documentos Electrónicos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SKU o código interno', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_tariff', models.CharField(default='2', help_text='Código impuesto SRI: 2=IVA, 3=ICE, etc.', max_length=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('unit_of_measure', models.CharField(default='N/A', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core_companies.company')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='facturacion_ec.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion_ec.product')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
            },
        ),
        migrations.CreateModel(
            name='SRISendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_xml', models.TextField(blank=True)),
                ('response_xml', models.TextField(blank=True)),
                ('response_code', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_logs', to='facturacion_ec.invoice')),
            ],
            options={
                'verbose_name': 'Log Envío SRI',
                'verbose_name_plural': 'Logs Envíos SRI',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha vencimiento (NULL = lifetime)', null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('payment_provider', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('transfer', 'Transferencia bancaria'), ('manual', 'Manual (registrado a mano)')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('invoices_this_month', models.IntegerField(default=0)),
                ('current_month_year', models.CharField(blank=True, max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion_licenses', to='core_companies.company')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion_ec.licensetype')),
            ],
            options={
                'verbose_name': 'Licencia de Empresa',
                'verbose_name_plural': 'Licencias de Empresas',
                'unique_together': {('company', 'license_type')},
            },
        ),
    ]
