# Generated by Django 5.0.14 on 2026-05-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='guia_remision_number',
            field=models.CharField(blank=True, help_text='Número de guía de remisión', max_length=50),
        ),
    ]
