# Generated by Django 5.0.14 on 2026-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_ec', '0002_invoice_guia_remision_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en línea', max_digits=12),
        ),
    ]
