# Generated by Django 5.0.14 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django.db.backends.base.operations",),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("template_key", models.CharField(max_length=50, unique=True)),
                ("html_template", models.TextField()),
                ("css_styles", models.TextField(blank=True, default="")),
                ("default_filename", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de Impresión",
                "verbose_name_plural": "Plantillas de Impresión",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("output_format", models.CharField(default="pdf", max_length=20)),
                (
                    "status",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True, blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="print_manager.printtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de Impresión",
                "verbose_name_plural": "Trabajos de Impresión",
                "ordering": ["-created_at"],
            },
        ),
    ]
