# Generated by Django 5.0.14 on 2026-04-01 04:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="Tipo de evento: 'invoice.created', 'payment.received', etc.", max_length=200)),
                ('source_module', models.CharField(help_text='Módulo que emitió el evento', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Datos del evento (serializado JSON)')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_events_event_t_42e86c_idx'), models.Index(fields=['source_module', 'created_at'], name='core_events_source__823f5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('subscriber_module', models.CharField(help_text='Módulo suscrito al evento', max_length=100)),
                ('handler_path', models.CharField(help_text="Ruta al handler: 'module.events.handle_event'", max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'verbose_name_plural': 'Event Subscriptions',
                'unique_together': {('event_type', 'subscriber_module')},
            },
        ),
    ]
