# Generated by Django 5.0.14 on 2026-05-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('inbox', 'Bandeja de entrada'), ('push', 'Push (futuro)')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body_template', models.TextField(help_text='Template con {{variables}} jinja2-style')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variables esperadas')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('inbox', 'Bandeja de entrada'), ('push', 'Push (futuro)')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notification_user_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('inbox', 'Bandeja de entrada'), ('push', 'Push (futuro)')], max_length=20)),
                ('recipient', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Cola de Notificación',
                'verbose_name_plural': 'Cola de Notificaciones',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notif_q_stats_created_idx')],
            },
        ),
    ]
